### ISSUE TITLE
download button doesn't work on Android 

### ISSUE THREAD

**Issue by HaarNhoo** [helloyanis/file-downloader-unleashed#5]
Hi 
I just install the latest version in firefox 132.0 (Build #2016051567), hg-0e15e2edd460+ on my Redmi note 13 pro +  phone.

The download button is changing in the menu extension but nothing happens when I tap on it.

Any help ?

**Comment by HaarNhoo** [comment]
ok, i understand the issue, and it's no big deal, maybe just a little patience still you find the trick to do it like the others plugins and the time tu update.
while the plugin is not working on android, maybe you just have to uncheck the available for android box hidden somewhere in the publications options.
thanks for your work and time.
Issue is closed for me.

**Comment by helloyanis** [comment]
Hello, yes I have unchecked this for the current version I just published today.

I had not tested but I thought I should include it anyways, so if it ended up working or people found a way to make it work, it would at least be there to install.

You should still try Seal, it's great for Android and I use it often!

**Comment by helloyanis** [comment]
It's compatible with Android now, @HaarNhoo give it a try!
